baseurl = "https://Mikaylaha.github.io"
title = "Homepage"
author = "Mikayla Hong"
canonifyurls = true
languagecode = "en"
theme = "hugo-tanka"

enableEmoji = true
hasCJKLanguage = false

pygmentsstyle = "vs"
pygmentscodefences = true

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]

[params]
  sitename = "Mikilaha"
  faviconfile = "images/favicon.png"
  highlightjs = true
  highlightjslanguages = ["r", "python", "stan"]
  uselatex = true
  progressively = false
# commentsrepo = "user/repo"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[[menu.primary]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.primary]]
    name = "About"
    url = "/about/"
    weight = 2
[[menu.primary]]
    name = "GitHub"
    url = "https://github.com/Mikaylaha"
    weight = 3
[[menu.primary]]
    name = "YouTube"
    url = "https://www.youtube.com/channel/UCJ79Yf4ExEluKiT2CTgEHOQ"
    weight = 4
[[menu.primary]]
    name = "Echoes"
    url = "https://echothejoy.wixsite.com/echoes"
    weight = 5
[[menu.primary]]
    name = "Info"
    url = "/Info/"
    weight = 6